export const restaurants = [
  {
    cod: 0,
    name: "Burger Shot",
    img: "https://cdn1.epicgames.com/ue/product/Screenshot/Image02-1920x1080-fa1a6bf20065289d788b7a0cd9d3df93.png?resize=1&w=1920",
    calification: 3,
    workTime: "09:30 - 23:00",
    pricesFrom: 4,
    foods: 1,
    description:
      "Especialistas en la preparación y venta de comcodas como hamburguesas, papas fritas, hot dogs, pizzas, ensaladas etc",
    timeDelivery: "15-20 min",
  },
  {
    cod: 1,
    name: "Pizzeria Carlo",
    img: "https://storage.googleapis.com/onmilwaukee-article-images/variants/pb1bo9jra9a0v7b1o99dvve5g3oy/ff35c9310a7d5016e76853b0df7d033449d793b6f6dc2e4a0b4bc844add6c385",
    calification: 4,
    workTime: "10:30 - 23:00",
    pricesFrom: 20,
    foods: 2,
    description:
      "Ofrecemos un menú variado que incluye pizzas clásicas como margarita, pepperoni, hawaiana, opciones vegetarianas, veganas y sin gluten ",
    timeDelivery: "30-50 min",
  },
  {
    cod: 2,
    name: "Last Stop",
    img: "https://toohotel.com/wp-content/uploads/2022/09/TOO_restaurant_Panoramique_vue_Paris_nuit_v2-scaled.jpg",
    calification: 5,
    workTime: "8:30 - 23:00",
    pricesFrom: 30,
    foods: 3,
    description:
      "los clientes pueden elegir entre una variedad de ensaladas, que pueden incluir lechugas variadas, verduras frescas.",
    timeDelivery: "1-2 horas",
  },
  {
    cod: 3,
    name: "La Pastisseria",
    img: "https://cdn.sortiraparis.com/images/80/100789/834071-too-restaurant-too-hotel-paris-photos-menu-entrees.jpg",
    calification: 4,
    workTime: "11:30 - 21:00",
    pricesFrom: 25,
    foods: 4,
    description:
      "Los clientes pueden elegir entre una variedad de pastas frescas, que pueden incluir fettuccine, spaghetti, penne, gnocchi, lasagna, entre otras.",
    timeDelivery: "1-2 horas",
  },
];

export const infoFoods = [
  {
    cod: 0,
    name: "Hamburguesa Clásica",
    img: "https://www.recetasnestle.com.ec/sites/default/files/srh_recipes/4e4293857c03d819e4ae51de1e86d66a.jpg",
    type: 0,
    restaurant: 0,
    price: 12000,
    description:
      " Hamburguesa de carne, queso cheddar, lechuga, tomate, cebolla y salsa especial.",
    aditions: [
      {
        cod: 0,
        name: "Tocineta",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 5000,
      },
      {
        cod: 2,
        name: "salsa BBQ",
        price: 2000,
      },
    ],
  },
  {
    cod: 1,
    name: "Hamburguesa BBQ",
    img: "https://chefeel.com/chefgeneralfiles/2022/06/burg-880x863.jpg",
    type: 0,
    restaurant: 0,
    price: 18000,
    description:
      "Hamburguesa de carne, queso cheddar, tocino, cebolla caramelizada, lechuga y salsa BBQ.",
    aditions: [
      {
        cod: 0,
        name: "Tocineta",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 5000,
      },
      {
        cod: 2,
        name: "salsa BBQ",
        price: 2000,
      },
    ],
  },
  {
    cod: 2,
    name: "Hamburguesa Mexicana",
    img: "https://merenderolasbrisas.co/wp-content/uploads/2017/10/Hamburguesa-Brisas-Mexicana1-2-7.jpg",
    type: 0,
    restaurant: 0,
    price: 22000,
    description:
      "Hamburguesa de carne, queso cheddar, jalapeños, guacamole, tomate y salsa picante.",
    aditions: [
      {
        cod: 0,
        name: "Tocineta",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 5000,
      },
      {
        cod: 2,
        name: "salsa BBQ",
        price: 2000,
      },
    ],
  },
  {
    cod: 3,
    name: "Hamburguesa vegetariana",
    img: "https://img2.rtve.es/imagenes/receta-hamburguesa-vegetariana/1625253973460.jpg",
    type: 0,
    restaurant: 0,
    price: 13000,
    description:
      "Hamburguesa de lentejas, queso de cabra, espinacas, tomate seco y salsa de yogur.",
    aditions: [
      {
        cod: 0,
        name: "Carne de lentejas",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 5000,
      },
      {
        cod: 2,
        name: "salsa de soya",
        price: 2000,
      },
    ],
  },
  {
    cod: 4,
    name: "Hamburguesa Hawaiana",
    img: "https://miraquereceta.com/wp-content/uploads/2020/07/Hamburguesa-hawaiana.png",
    type: 0,
    restaurant: 0,
    price: 13000,
    description:
      "Hamburguesa de pollo, queso cheddar, piña, lechuga y salsa teriyaki.",
    aditions: [
      {
        cod: 0,
        name: "Tocineta",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 5000,
      },
      {
        cod: 2,
        name: "salsa BBQ",
        price: 2000,
      },
    ],
  },
  {
    cod: 5,
    name: "Hamburguesa Deluxe",
    img: "https://www.elespectador.com/resizer/GTaYjwYgjDhrZyiy2WyadYurt-4=/arc-anglerfish-arc2-prod-elespectador/public/N5EPKUWMIVH4RCPNDM7OP5OKQQ.jpeg",
    type: 0,
    restaurant: 0,
    price: 20000,
    description:
      "Hamburguesa de carne, queso azul, tocino, huevo frito, lechuga y mayonesa.",
    aditions: [
      {
        cod: 0,
        name: "Tocineta",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso Azúl",
        price: 8000,
      },
      {
        cod: 2,
        name: "Maices cremosos",
        price: 5000,
      },
    ],
  },
  {
    cod: 6,
    name: "Papas Parmesanas",
    img: "http://assets.kraftfoods.com/recipe_images/opendeploy/201858_640x428.jpg",
    type: 1,
    restaurant: 0,
    price: 18000,
    description: "Papas fritas con queso parmesano rallado y hierbas.",
    aditions: [
      {
        cod: 0,
        name: "Salchicha ranchera",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 8000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 7,
    name: "Papas Ajo y hierbas",
    img: "https://www.recetin.com/wp-content/uploads/2013/09/patatas_especias.jpg",
    type: 1,
    restaurant: 0,
    price: 15000,
    description:
      "Papas fritas con ajo picado y hierbas frescas como tomillo o romero.",
    aditions: [
      {
        cod: 0,
        name: "Salchicha ranchera",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 8000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 8,
    name: "Papas Dulces",
    img: "https://images.cookforyourlife.org/wp-content/uploads/2015/08/shutterstock_762822427-Savory-Sweet-Potato-Fries.jpg",
    type: 1,
    restaurant: 0,
    price: 17000,
    description:
      "Papas fritas de batata o camote, sazonadas con canela y azúcar.",
    aditions: [
      {
        cod: 0,
        name: "Salchicha ranchera",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 8000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 9,
    name: "Papas Cajún",
    img: "https://okdiario.com/img/2019/08/15/receta-de-patatas-cajun-al-microondas.jpg",
    type: 1,
    restaurant: 0,
    price: 23000,
    description: "Papas fritas sazonadas con una mezcla de especias cajún.",
    aditions: [
      {
        cod: 0,
        name: "Salchicha ranchera",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 8000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 10,
    name: "Papas cargadas",
    img: "https://dopeysden.com/wp-content/uploads/2022/06/image-3-683x1024.png",
    type: 1,
    restaurant: 0,
    price: 25000,
    description:
      "Papas fritas cubiertas con queso cheddar, tocino y cebolla verde.",
    aditions: [
      {
        cod: 0,
        name: "Salchicha ranchera",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 8000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 11,
    name: "Papas Clásicas",
    img: "https://img-global.cpcdn.com/recipes/eda404215497cd6c/680x482cq70/papas-clasicas-al-horno-con-tips-foto-principal.jpg",
    type: 1,
    restaurant: 0,
    price: 12000,
    description: "Papas fritas cortadas en bastones y sazonadas con sal.",
    aditions: [
      {
        cod: 0,
        name: "Salchicha ranchera",
        price: 4000,
      },
      {
        cod: 1,
        name: "Queso",
        price: 8000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 12,
    name: "Burrito de cerdo",
    img: "https://www.goya.com/media/4141/chipotle-pork-burritos.jpg?quality=80",
    type: 2,
    restaurant: 0,
    price: 12000,
    description: "Cerdo asado, arroz, frijoles, queso, lechuga y salsa.",
    aditions: [
      {
        cod: 0,
        name: "Chorizo argentino",
        price: 3000,
      },
      {
        cod: 1,
        name: "Queso Chedar",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 13,
    name: "Burrito de pollo",
    img: "https://www.pequerecetas.com/wp-content/uploads/2012/01/burritos-de-pollo.jpg",
    type: 2,
    restaurant: 0,
    price: 9000,
    description:
      "Pollo a la parrilla, arroz, frijoles negros, queso, lechuga y salsa.",
    aditions: [
      {
        cod: 0,
        name: "Queso crema",
        price: 3000,
      },
      {
        cod: 1,
        name: "Queso Azúl",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 14,
    name: "Burrito clásico",
    img: "https://d1kxxrc2vqy8oa.cloudfront.net/wp-content/uploads/2020/01/09213530/RFB-2312-1-burrito.jpg",
    type: 2,
    restaurant: 0,
    price: 8000,
    description:
      "Carne de res, frijoles negros, arroz, queso, lechuga y salsa.",
    aditions: [
      {
        cod: 0,
        name: "Queso crema",
        price: 3000,
      },
      {
        cod: 1,
        name: "Queso Azúl",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 15,
    name: "Burrito vegetariano",
    img: "https://assets.epicurious.com/photos/57978b27c9298e54495917d5/master/w_1000,h_662,c_limit/black-bean-and-vegetable-burritos.jpg",
    type: 2,
    restaurant: 0,
    price: 9000,
    description:
      "Tofu o falafel, arroz integral, frijoles, aguacate, lechuga y salsa.",
    aditions: [
      {
        cod: 0,
        name: "Queso crema",
        price: 3000,
      },
      {
        cod: 1,
        name: "Queso Azúl",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tofu",
        price: 5000,
      },
    ],
  },
  {
    cod: 16,
    name: "Burrito de camarones",
    img: "https://tofuu.getjusto.com/orioneat-local/resized2/CY39TZpJNDNxEF7YD-1200-1200.webp",
    type: 2,
    restaurant: 0,
    price: 21000,
    description:
      "Camarones salteados, arroz, frijoles, queso, lechuga y salsa.",
    aditions: [
      {
        cod: 0,
        name: "Queso crema",
        price: 3000,
      },
      {
        cod: 1,
        name: "Queso Azúl",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 17,
    name: "Burrito de desayuno",
    img: "https://www.goya.com/media/3172/black-bean-breakfast-burritos.jpg?quality=80",
    type: 2,
    restaurant: 0,
    price: 9000,
    description:
      "Huevos revueltos, tocino, papas fritas, queso, tomate y salsa.",
    aditions: [
      {
        cod: 0,
        name: "Queso crema",
        price: 3000,
      },
      {
        cod: 1,
        name: "Queso Azúl",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
    ],
  },
  {
    cod: 18,
    name: "Pizza Margarita",
    img: "https://cdn.colombia.com/gastronomia/2011/08/25/pizza-margarita-3684-1.jpg",
    type: 0,
    restaurant: 1,
    price: 13000,
    description:
      "Salsa de tomate, mozzarella fresca, albahaca y aceite de oliva.",
    aditions: [
      {
        cod: 0,
        name: "Tocino",
        price: 7000,
      },
      {
        cod: 1,
        name: "Carne",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
      {
        cod: 3,
        name: "Aceitunas",
        price: 2000,
      },
      {
        cod: 4,
        name: "Anchoas",
        price: 3000,
      },
      {
        cod: 5,
        name: "Salchicha",
        price: 6000,
      },
      {
        cod: 6,
        name: "Tomate seco",
        price: 3000,
      },
      {
        cod: 7,
        name: "Champiñones",
        price: 5000,
      },
    ],
  },
  {
    cod: 19,
    name: "Pizza Hawaiana",
    img: "https://napolicartagena.com/wp-content/uploads/2022/01/La-Pizza-Hawaiana-de-Canada.jpg",
    type: 0,
    restaurant: 1,
    price: 15000,
    description: "Salsa de tomate, mozzarella, jamón, piña y jalapeños.",
    aditions: [
      {
        cod: 0,
        name: "Tocino",
        price: 7000,
      },
      {
        cod: 1,
        name: "Carne",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
      {
        cod: 3,
        name: "Aceitunas",
        price: 2000,
      },
      {
        cod: 4,
        name: "Anchoas",
        price: 3000,
      },
      {
        cod: 5,
        name: "Salchicha",
        price: 6000,
      },
      {
        cod: 6,
        name: "Tomate seco",
        price: 3000,
      },
      {
        cod: 7,
        name: "Champiñones",
        price: 5000,
      },
    ],
  },
  {
    cod: 20,
    name: "Pizza Cuatro Quesos",
    img: "https://www.cocinatis.com/archivos/202207/CTIS0093-receta-pizza-cuatro-quesos_B3N6zYV_large_16x9.jpg",
    type: 0,
    restaurant: 1,
    price: 23000,
    description: "Mozzarella, queso gorgonzola, queso brie y queso parmesano.",
    aditions: [
      {
        cod: 0,
        name: "Tocino",
        price: 7000,
      },
      {
        cod: 1,
        name: "Carne",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
      {
        cod: 3,
        name: "Aceitunas",
        price: 2000,
      },
      {
        cod: 4,
        name: "Anchoas",
        price: 3000,
      },
      {
        cod: 5,
        name: "Salchicha",
        price: 6000,
      },
      {
        cod: 6,
        name: "Tomate seco",
        price: 3000,
      },
      {
        cod: 7,
        name: "Champiñones",
        price: 5000,
      },
    ],
  },
  {
    cod: 21,
    name: "Pizza Barbacoa",
    img: "https://www.unileverfoodsolutions.es/dam/global-ufs/mcos/SPAIN/calcmenu/recipes/ES-recipes/general/pizza-barbacoa/main-header.jpg",
    type: 0,
    restaurant: 1,
    price: 25000,
    description:
      "Salsa de barbacoa, mozzarella, pollo a la parrilla, cebolla y cilantro.",
    aditions: [
      {
        cod: 0,
        name: "Tocino",
        price: 7000,
      },
      {
        cod: 1,
        name: "Carne",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
      {
        cod: 3,
        name: "Aceitunas",
        price: 2000,
      },
      {
        cod: 4,
        name: "Anchoas",
        price: 3000,
      },
      {
        cod: 5,
        name: "Salchicha",
        price: 6000,
      },
      {
        cod: 6,
        name: "Tomate seco",
        price: 3000,
      },
      {
        cod: 7,
        name: "Champiñones",
        price: 5000,
      },
    ],
  },
  {
    cod: 22,
    name: "Pizza Vegetariana",
    img: "https://chacarabertolin.com.br/wp-content/uploads/2018/07/pizza-frango-pimentao.jpg",
    type: 0,
    restaurant: 1,
    price: 20000,
    description:
      "Salsa de tomate, mozzarella, champiñones, pimientos, cebolla y aceitunas.",
    aditions: [
      {
        cod: 0,
        name: "Tocino",
        price: 7000,
      },
      {
        cod: 1,
        name: "Carne",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
      {
        cod: 3,
        name: "Aceitunas",
        price: 2000,
      },
      {
        cod: 4,
        name: "Anchoas",
        price: 3000,
      },
      {
        cod: 5,
        name: "Salchicha",
        price: 6000,
      },
      {
        cod: 6,
        name: "Tomate seco",
        price: 3000,
      },
      {
        cod: 7,
        name: "Champiñones",
        price: 5000,
      },
    ],
  },
  {
    cod: 23,
    name: "Pizza Pepperoni",
    img: "https://images.hola.com/imagenes/cocina/recetas/20220208204252/pizza-pepperoni-mozzarella/1-48-890/pepperoni-pizza-abob-t.jpg",
    type: 0,
    restaurant: 1,
    price: 24000,
    description: "Salsa de tomate, mozzarella y pepperoni.",
    aditions: [
      {
        cod: 0,
        name: "Tocino",
        price: 7000,
      },
      {
        cod: 1,
        name: "Carne",
        price: 6000,
      },
      {
        cod: 2,
        name: "Tocineta",
        price: 5000,
      },
      {
        cod: 3,
        name: "Aceitunas",
        price: 2000,
      },
      {
        cod: 4,
        name: "Anchoas",
        price: 3000,
      },
      {
        cod: 5,
        name: "Salchicha",
        price: 6000,
      },
      {
        cod: 6,
        name: "Tomate seco",
        price: 3000,
      },
      {
        cod: 7,
        name: "Champiñones",
        price: 5000,
      },
    ],
  },
  {
    cod: 24,
    name: "Quesadilla de pollo",
    img: "https://www.recetasdejusticia.com/wp-content/uploads/2021/01/Receta_de_quesadillas_de_pollo.jpg",
    type: 1,
    restaurant: 1,
    price: 9000,
    description:
      "Pollo a la parrilla, queso cheddar y queso Monterey Jack en una tortilla de harina.",
    aditions: [
      {
        cod: 0,
        name: "Jalapeños",
        price: 3000,
      },
      {
        cod: 1,
        name: "Tomates dulces",
        price: 6000,
      },
      {
        cod: 2,
        name: "Aguacate",
        price: 5000,
      },
    ],
  },
  {
    cod: 25,
    name: "Quesadilla de verduras",
    img: "https://cdn2.cocinadelirante.com/sites/default/files/images/2016/09/quesadillaconverduras2_0.jpg",
    type: 1,
    restaurant: 1,
    price: 15000,
    description:
      "Una mezcla de vegetales a la parrilla (como calabacín, pimiento y cebolla), queso cheddar y queso Monterey Jack en una tortilla de harina.",
    aditions: [
      {
        cod: 0,
        name: "Jalapeños",
        price: 3000,
      },
      {
        cod: 1,
        name: "Tomates dulces",
        price: 6000,
      },
      {
        cod: 2,
        name: "Aguacate",
        price: 5000,
      },
    ],
  },
  {
    cod: 26,
    name: "Quesadilla de carne asada",
    img: "https://familiakitchen.com/wp-content/uploads/2022/07/iStock-1320209199-Anjie-quesadillas-carne-asada-3.jpg",
    type: 1,
    restaurant: 1,
    price: 26000,
    description:
      "Carne asada a la parrilla, queso cheddar y queso Monterey Jack en una tortilla de harina.",
    aditions: [
      {
        cod: 0,
        name: "Jalapeños",
        price: 3000,
      },
      {
        cod: 1,
        name: "Tomates dulces",
        price: 6000,
      },
      {
        cod: 2,
        name: "Aguacate",
        price: 5000,
      },
    ],
  },
  {
    cod: 27,
    name: "Quesadilla de camarones",
    img: "https://tropicalcheese.com/wp-content/uploads/2019/03/cheese-shrimp-avocado-quesadilla-1280x640.jpg",
    type: 1,
    restaurant: 1,
    price: 19000,
    description:
      "Camarones a la parrilla, queso cheddar y queso Monterey Jack en una tortilla de harina.",
    aditions: [
      {
        cod: 0,
        name: "Jalapeños",
        price: 3000,
      },
      {
        cod: 1,
        name: "Tomates dulces",
        price: 6000,
      },
      {
        cod: 2,
        name: "Aguacate",
        price: 5000,
      },
    ],
  },
  {
    cod: 28,
    name: "Quesadilla champiñones",
    img: "https://unareceta.com/wp-content/uploads/2016/08/receta-Quesadilla-de-champi%C3%B1ones.jpg",
    type: 1,
    restaurant: 1,
    price: 19000,
    description:
      "Espinacas, champiñones, queso cheddar y queso Monterey Jack en una tortilla de harina.",
    aditions: [
      {
        cod: 0,
        name: "Jalapeños",
        price: 3000,
      },
      {
        cod: 1,
        name: "Tomates dulces",
        price: 6000,
      },
      {
        cod: 2,
        name: "Aguacate",
        price: 5000,
      },
    ],
  },
  {
    cod: 29,
    name: "Quesadilla jamón y queso",
    img: "http://estoyhechouncocinillas.com/wp-content/uploads/2021/04/quesadillas-de-jamon-y-queso-sincronizadas.jpg",
    type: 1,
    restaurant: 1,
    price: 12000,
    description:
      "Jamón y queso cheddar y queso Monterey Jack en una tortilla de harina.",
    aditions: [
      {
        cod: 0,
        name: "Jalapeños",
        price: 3000,
      },
      {
        cod: 1,
        name: "Tomates dulces",
        price: 6000,
      },
      {
        cod: 2,
        name: "Aguacate",
        price: 5000,
      },
    ],
  },
  {
    cod: 30,
    name: "Alitas tradicionales",
    img: "https://www.recetasderechupete.com/wp-content/uploads/2018/06/alitas-de-pollo-horno.jpg",
    type: 2,
    restaurant: 1,
    price: 18000,
    description:
      "Alas de pollo fritas con una salsa picante, ajo y mantequilla.",
    aditions: [
      {
        cod: 0,
        name: "Salsa de ajo",
        price: 2000,
      },
      {
        cod: 1,
        name: "Miel mostaza",
        price: 3000,
      },
      {
        cod: 2,
        name: "Cayena",
        price: 5000,
      },
    ],
  },
  {
    cod: 31,
    name: "Alitas BBQ",
    img: "https://assets.unileversolutions.com/recipes-v2/231986.jpg",
    type: 2,
    restaurant: 1,
    price: 20000,
    description:
      "Alas de pollo cubiertas con salsa BBQ y a la parrilla o al horno.",
    aditions: [
      {
        cod: 0,
        name: "Salsa de ajo",
        price: 2000,
      },
      {
        cod: 1,
        name: "Miel mostaza",
        price: 3000,
      },
      {
        cod: 2,
        name: "Cayena",
        price: 5000,
      },
    ],
  },
  {
    cod: 32,
    name: "Alitas asiáticas",
    img: "https://editorialtelevisa.brightspotcdn.com/wp-content/uploads/2021/02/como-preparar-alitas-de-pollo-asiaticas.jpg",
    type: 2,
    restaurant: 1,
    price: 27000,
    description:
      "Alas de pollo fritas con una salsa picante y cremosa, generalmente acompañadas de zanahoria y apio fresco.",
    aditions: [
      {
        cod: 0,
        name: "Salsa de ajo",
        price: 2000,
      },
      {
        cod: 1,
        name: "Miel mostaza",
        price: 3000,
      },
      {
        cod: 2,
        name: "Cayena",
        price: 5000,
      },
    ],
  },
  {
    cod: 33,
    name: "Alitas Buffalo",
    img: "https://www.deliciosi.com/images/1100/1197/alitas-de-pollo-picantes.jpg",
    type: 2,
    restaurant: 1,
    price: 23000,
    description:
      "Alas de pollo fritas con una salsa picante y cremosa, generalmente acompañadas de zanahoria y apio fresco.",
    aditions: [
      {
        cod: 0,
        name: "Salsa de ajo",
        price: 2000,
      },
      {
        cod: 1,
        name: "Miel mostaza",
        price: 3000,
      },
      {
        cod: 2,
        name: "Cayena",
        price: 5000,
      },
    ],
  },
  {
    cod: 34,
    name: "Alitas teriyaki",
    img: "https://i.blogs.es/e9b585/alitas-teriyaki-180317-0001/450_1000.jpg",
    type: 2,
    restaurant: 1,
    price: 25000,
    description:
      "Alas de pollo fritas o asadas con salsa teriyaki y semillas de sésamo.",
    aditions: [
      {
        cod: 0,
        name: "Salsa de ajo",
        price: 2000,
      },
      {
        cod: 1,
        name: "Miel mostaza",
        price: 3000,
      },
      {
        cod: 2,
        name: "Cayena",
        price: 5000,
      },
    ],
  },
  {
    cod: 35,
    name: "Alitas limón y pimienta",
    img: "https://img.bylauragarcia.com/contenedorblog/bbfa2501-64c5-4a04-a937-1fba71b3ed2e_alitasdepollo2.jpg",
    type: 2,
    restaurant: 1,
    price: 24000,
    description:
      "Alas de pollo asadas o fritas con un adobo de limón y pimienta.",
    aditions: [
      {
        cod: 0,
        name: "Salsa de ajo",
        price: 2000,
      },
      {
        cod: 1,
        name: "Miel mostaza",
        price: 3000,
      },
      {
        cod: 2,
        name: "Cayena",
        price: 5000,
      },
    ],
  },
  {
    cod: 36,
    name: "Ensalada César",
    img: "https://cecotec.es/recetas/wp-content/uploads/2022/11/Cecofry_Ensalada-Cesar_ligera_RRSS-1.jpg",
    type: 0,
    restaurant: 2,
    price: 30000,
    description:
      "Lechuga romana, pollo a la parrilla, croutones, queso parmesano y aderezo César.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Tofu",
        price: 4000,
      },
      {
        cod: 2,
        name: "Carne",
        price: 7000,
      },
    ],
  },
  {
    cod: 37,
    name: "Ensalada Mediterránea",
    img: "https://elmen.pe/wp-content/uploads/2022/01/Ensalada-mediterranea.jpg",
    type: 0,
    restaurant: 2,
    price: 45000,
    description:
      "Lechuga mixta, tomates cherry, pepino, aceitunas, queso feta y aderezo de vinagreta.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Tofu",
        price: 4000,
      },
      {
        cod: 2,
        name: "Carne",
        price: 7000,
      },
    ],
  },
  {
    cod: 38,
    name: "Ensalada de pollo y aguacate",
    img: "https://okdiario.com/img/2019/08/10/receta-de-ensalada-con-aguacate-y-pollo-asado-1-655x368.jpg",
    type: 0,
    restaurant: 2,
    price: 25000,
    description:
      "Lechuga, pollo a la parrilla, aguacate, tomate, cebolla roja y aderezo ranch.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Tofu",
        price: 4000,
      },
      {
        cod: 2,
        name: "Carne",
        price: 7000,
      },
    ],
  },
  {
    cod: 39,
    name: "Ensalada de espinacas y fresas",
    img: "https://es.rc-cdn.community.thermomix.com/recipeimage/fqj2iquj-3e299-490562-88c8b-ing5uf77/05addd97-c10b-4725-a176-611c54e1458a/large/ensalada-de-espinacas-con-fresas-y-nueces.png",
    type: 0,
    restaurant: 2,
    price: 50000,
    description:
      "Espinacas frescas, fresas, queso de cabra, nueces caramelizadas y aderezo balsámico.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Tofu",
        price: 4000,
      },
      {
        cod: 2,
        name: "Carne",
        price: 7000,
      },
    ],
  },
  {
    cod: 40,
    name: "Ensalada de atún",
    img: "https://t2.uc.ltmcdn.com/es/posts/5/4/4/como_hacer_ensalada_de_atun_51445_orig.jpg",
    type: 0,
    restaurant: 2,
    price: 55000,
    description:
      "Lechuga, atún enlatado, huevo duro, tomate, pepino y aderezo de mostaza y miel.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Tofu",
        price: 4000,
      },
      {
        cod: 2,
        name: "Carne",
        price: 7000,
      },
    ],
  },
  {
    cod: 41,
    name: "Ensalada de col y zanahoria",
    img: "https://recetasconzanahoria.com/wp-content/uploads/2020/08/ensalada-repollo-zanahoria.jpg",
    type: 0,
    restaurant: 2,
    price: 28000,
    description:
      "Repollo y zanahoria rallados, pasas, manzana y aderezo de mayonesa y vinagre.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 42,
    name: "Sopa de tomate",
    img: "https://t1.uc.ltmcdn.com/es/posts/3/0/9/como_hacer_sopa_de_tomate_casera_25903_orig.jpg",
    type: 1,
    restaurant: 2,
    price: 19000,
    description:
      "Sopa cremosa hecha con tomates frescos, cebolla y ajo, generalmente acompañada de croutones o pan tostado.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Carne de res",
        price: 6000,
      },
      {
        cod: 4,
        name: "Papas salteadas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Zanahorias",
        price: 6000,
      },
      {
        cod: 6,
        name: "Apio",
        price: 6000,
      },
    ],
  },
  {
    cod: 43,
    name: "Sopa de champiñones",
    img: "https://images.hola.com/imagenes/cocina/recetas/20191023152380/sopa-de-champinones/0-737-313/sopa-champi-adobe-m.jpg",
    type: 1,
    restaurant: 2,
    price: 21000,
    description:
      "Sopa cremosa hecha con champiñones, cebolla y caldo de pollo, generalmente servcoda con pan tostado.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Carne de res",
        price: 6000,
      },
      {
        cod: 4,
        name: "Papas salteadas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Zanahorias",
        price: 6000,
      },
      {
        cod: 6,
        name: "Apio",
        price: 6000,
      },
    ],
  },
  {
    cod: 44,
    name: "Sopa de lentejas",
    img: "https://imag.bonviveur.com/sopa-de-lentejas.jpg",
    type: 1,
    restaurant: 2,
    price: 24000,
    description:
      "Sopa hecha con lentejas, verduras y especias, generalmente servcoda con pan.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Carne de res",
        price: 6000,
      },
      {
        cod: 4,
        name: "Papas salteadas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Zanahorias",
        price: 6000,
      },
      {
        cod: 6,
        name: "Apio",
        price: 6000,
      },
    ],
  },
  {
    cod: 45,
    name: "Sopa de pollo y verduras",
    img: "https://cocina-casera.com/wp-content/uploads/2017/12/Sopa-de-pollo.jpg",
    type: 1,
    restaurant: 2,
    price: 26000,
    description:
      " Sopa hecha con pollo, verduras y fcodeos, generalmente servcoda con pan.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Carne de res",
        price: 6000,
      },
      {
        cod: 4,
        name: "Papas salteadas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Zanahorias",
        price: 6000,
      },
      {
        cod: 6,
        name: "Apio",
        price: 6000,
      },
    ],
  },
  {
    cod: 46,
    name: "Sopa de maíz",
    img: "https://www.recetasderechupete.com/wp-content/uploads/2021/04/Corn-Chowder-1.jpg",
    type: 1,
    restaurant: 2,
    price: 28000,
    description:
      "Sopa cremosa hecha con maíz fresco, leche y especias, generalmente servcoda con tortilla chips o pan tostado.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Carne de res",
        price: 6000,
      },
      {
        cod: 4,
        name: "Papas salteadas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Zanahorias",
        price: 6000,
      },
      {
        cod: 6,
        name: "Apio",
        price: 6000,
      },
    ],
  },
  {
    cod: 47,
    name: "Sopa de cebolla",
    img: "https://images.hola.com/imagenes/cocina/recetas/20191115153963/sopa-cebolla-gratinada-queso/0-745-600/sopa-cebolla-adobe-m.jpg",
    type: 1,
    restaurant: 2,
    price: 22000,
    description:
      "Sopa hecha con cebolla caramelizada y caldo de carne, generalmente cubierta con queso gratinado y servcoda con pan tostado.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Carne de res",
        price: 6000,
      },
      {
        cod: 4,
        name: "Papas salteadas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Zanahorias",
        price: 6000,
      },
      {
        cod: 6,
        name: "Apio",
        price: 6000,
      },
    ],
  },
  {
    cod: 48,
    name: "Frutas del bosque",
    img: "https://www.comedera.com/wp-content/uploads/2022/05/batidos-frutas-del-bosque.jpg",
    type: 2,
    restaurant: 2,
    price: 12000,
    description:
      "Sopa hecha con cebolla caramelizada y caldo de carne, generalmente cubierta con queso gratinado y servcoda con pan tostado.",
    aditions: [
      {
        cod: 0,
        name: "Proteina",
        price: 7000,
      },
      {
        cod: 1,
        name: "Avena",
        price: 2000,
      },
      {
        cod: 2,
        name: "Miel",
        price: 2000,
      },
      {
        cod: 3,
        name: "Jarabe de arce",
        price: 6000,
      },
      {
        cod: 4,
        name: "Jengibre",
        price: 3000,
      },
      {
        cod: 5,
        name: "Canela",
        price: 2000,
      },
    ],
  },
  {
    cod: 49,
    name: "Plátano y maní",
    img: "https://www.gastrolabweb.com/u/fotografias/m/2021/6/16/f850x638-14846_92335_6842.jpg",
    type: 2,
    restaurant: 2,
    price: 14000,
    description:
      " Batcodo hecho con plátanos maduros, mantequilla de maní, leche o yogurt, y hielo.",
    aditions: [
      {
        cod: 0,
        name: "Proteina",
        price: 7000,
      },
      {
        cod: 1,
        name: "Avena",
        price: 2000,
      },
      {
        cod: 2,
        name: "Miel",
        price: 2000,
      },
      {
        cod: 3,
        name: "Jarabe de arce",
        price: 6000,
      },
      {
        cod: 4,
        name: "Jengibre",
        price: 3000,
      },
      {
        cod: 5,
        name: "Canela",
        price: 2000,
      },
    ],
  },
  {
    cod: 50,
    name: "Mango y coco",
    img: "https://www.cocinavital.mx/wp-content/uploads/2017/08/licuadodemangoconcremadecoco.jpg",
    type: 2,
    restaurant: 2,
    price: 16000,
    description: "Batcodo hecho con mango fresco, leche de coco, miel y hielo.",
    aditions: [
      {
        cod: 0,
        name: "Proteina",
        price: 7000,
      },
      {
        cod: 1,
        name: "Avena",
        price: 2000,
      },
      {
        cod: 2,
        name: "Miel",
        price: 2000,
      },
      {
        cod: 3,
        name: "Jarabe de arce",
        price: 6000,
      },
      {
        cod: 4,
        name: "Jengibre",
        price: 3000,
      },
      {
        cod: 5,
        name: "Canela",
        price: 2000,
      },
    ],
  },
  {
    cod: 51,
    name: "Piña y espinaca",
    img: "https://cocinarconrobot.com/wp-content/uploads/batido-pina-espinacas-naranja-thermomix.jpg",
    type: 2,
    restaurant: 2,
    price: 19000,
    description:
      "Batcodo hecho con piña fresca, espinacas, leche o yogurt y hielo.",
    aditions: [
      {
        cod: 0,
        name: "Proteina",
        price: 7000,
      },
      {
        cod: 1,
        name: "Avena",
        price: 2000,
      },
      {
        cod: 2,
        name: "Miel",
        price: 2000,
      },
      {
        cod: 3,
        name: "Jarabe de arce",
        price: 6000,
      },
      {
        cod: 4,
        name: "Jengibre",
        price: 3000,
      },
      {
        cod: 5,
        name: "Canela",
        price: 2000,
      },
    ],
  },
  {
    cod: 52,
    name: "Chocolate",
    img: "https://www.lactaidenespanol.com/sites/lactaid_us/files/recipe-images/easy_chocolate_shakes.jpg",
    type: 2,
    restaurant: 2,
    price: 15000,
    description:
      "Batcodo hecho con leche, helado de chocolate, cacao en polvo y hielo.",
    aditions: [
      {
        cod: 0,
        name: "Proteina",
        price: 7000,
      },
      {
        cod: 1,
        name: "Avena",
        price: 2000,
      },
      {
        cod: 2,
        name: "Miel",
        price: 2000,
      },
      {
        cod: 3,
        name: "Jarabe de arce",
        price: 6000,
      },
      {
        cod: 4,
        name: "Jengibre",
        price: 3000,
      },
      {
        cod: 5,
        name: "Canela",
        price: 2000,
      },
    ],
  },
  {
    cod: 53,
    name: "Café",
    img: "https://recetasdebatidos.com/wp-content/uploads/2018/07/Batido-de-cafe%CC%81-con-hielo-2.jpg",
    type: 2,
    restaurant: 2,
    price: 13000,
    description:
      "Batcodo hecho con café frío, leche, helado de vainilla y hielo.",
    aditions: [
      {
        cod: 0,
        name: "Proteina",
        price: 7000,
      },
      {
        cod: 1,
        name: "Avena",
        price: 2000,
      },
      {
        cod: 2,
        name: "Miel",
        price: 2000,
      },
      {
        cod: 3,
        name: "Jarabe de arce",
        price: 6000,
      },
      {
        cod: 4,
        name: "Jengibre",
        price: 3000,
      },
      {
        cod: 5,
        name: "Canela",
        price: 2000,
      },
    ],
  },

  {
    cod: 54,
    name: "Spaghetti a la boloñesa",
    img: "https://assets.unileversolutions.com/recipes-v2/118368.jpg",
    type: 0,
    restaurant: 3,
    price: 18000,
    description: "Spaghetti con salsa de tomate y carne molcoda.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 55,
    name: "Linguine con almejas",
    img: "https://recetaspasta.com/wp-content/uploads/2019/04/Linguini-con-almejas.jpg",
    type: 0,
    restaurant: 3,
    price: 22000,
    description: "Linguine con almejas en salsa de vino blanco y ajo.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 56,
    name: "Penne arrabiata",
    img: "https://natashaskitchen.com/wp-content/uploads/2023/02/Penne-alla-Vodka-SQ.jpg",
    type: 0,
    restaurant: 3,
    price: 15000,
    description: "Penne con salsa de tomate picante, ajo y aceite de oliva.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 57,
    name: "Fettuccine Alfredo",
    img: "https://plantbasedonabudget.com/wp-content/uploads/2020/10/Fettuccine-Alfredo-Plant-Based-on-a-Budget-1-2-500x500.jpg",
    type: 0,
    restaurant: 3,
    price: 25000,
    description:
      "Fettuccine en una salsa cremosa de mantequilla y queso parmesano.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 58,
    name: "Lasagna",
    img: "https://bakingmischief.com/wp-content/uploads/2021/11/easy-lasagna-image-square-2.jpg",
    type: 0,
    restaurant: 3,
    price: 27000,
    description:
      "Capas de pasta con salsa de carne, queso ricotta y mozzarella.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 59,
    name: "Rigatoni con vegetales",
    img: "https://www.confiesoquecocino.com/wp-content/uploads/2018/04/pasta-con-verduras-salteadas-portada.jpg",
    type: 0,
    restaurant: 3,
    price: 19000,
    description:
      "Capas de pasta con salsa de carne, queso ricotta y mozzarella.",
    aditions: [
      {
        cod: 0,
        name: "Salmón",
        price: 12000,
      },
      {
        cod: 1,
        name: "Pollo",
        price: 7000,
      },
      {
        cod: 2,
        name: "Camarones",
        price: 15000,
      },
      {
        cod: 3,
        name: "Tomates secos",
        price: 4000,
      },
      {
        cod: 4,
        name: "Aceitunas",
        price: 6000,
      },
      {
        cod: 5,
        name: "Esparragos",
        price: 6000,
      },
    ],
  },
  {
    cod: 60,
    name: "Pan francés",
    img: "https://queapetito.com/wp-content/uploads/2019/09/baguettes-1-600x469.jpg",
    type: 1,
    restaurant: 3,
    price: 12000,
    description:
      "Un pan de estilo clásico, crujiente por fuera y suave por dentro, perfecto para acompañar una cena o para hacer un sándwich.",
    aditions: [
      {
        cod: 0,
        name: "Queso",
        price: 4000,
      },
      {
        cod: 1,
        name: "Salami",
        price: 7000,
      },
      {
        cod: 2,
        name: "Jamón",
        price: 5000,
      },
    ],
  },
  {
    cod: 61,
    name: "Pan de maíz",
    img: "https://www.goya.com/media/3991/skillet-cornbread.jpg?quality=80",
    type: 1,
    restaurant: 3,
    price: 15000,
    description:
      "Un pan hecho con harina de maíz, perfecto para acompañar una cena de barbacoa o una sopa.",
    aditions: [
      {
        cod: 0,
        name: "Queso",
        price: 4000,
      },
      {
        cod: 1,
        name: "Salami",
        price: 7000,
      },
      {
        cod: 2,
        name: "Jamón",
        price: 5000,
      },
    ],
  },
  {
    cod: 62,
    name: "Pan de ajo",
    img: "https://cdn.elcocinerocasero.com/imagen/receta/1000/2015-10-22-12-10-18/pan-de-ajo.jpeg",
    type: 1,
    restaurant: 3,
    price: 15000,
    description:
      "Un pan cubierto de ajo y mantequilla, perfecto como acompañamiento para la pasta o la pizza.",
    aditions: [
      {
        cod: 0,
        name: "Queso",
        price: 4000,
      },
      {
        cod: 1,
        name: "Salami",
        price: 7000,
      },
      {
        cod: 2,
        name: "Jamón",
        price: 5000,
      },
    ],
  },
  {
    cod: 63,
    name: "Baguette",
    img: "https://sivarious.com/wp-content/uploads/2022/03/pan-baguette-casera.jpg",
    type: 1,
    restaurant: 3,
    price: 18000,
    description:
      "Un pan largo y delgado de origen francés, perfecto para hacer bocadillos o para acompañar la cena.",
    aditions: [
      {
        cod: 0,
        name: "Queso",
        price: 4000,
      },
      {
        cod: 1,
        name: "Salami",
        price: 7000,
      },
      {
        cod: 2,
        name: "Jamón",
        price: 5000,
      },
    ],
  },
  {
    cod: 64,
    name: "Pan de nueces",
    img: "https://www.comedera.com/wp-content/uploads/2022/03/loaf-gfe57a13af_1920.jpg",
    type: 1,
    restaurant: 3,
    price: 20000,
    description:
      "Un pan hecho con nueces y pasas, perfecto para acompañar un queso o como acompañamiento para la cena.",
    aditions: [
      {
        cod: 0,
        name: "Queso",
        price: 4000,
      },
      {
        cod: 1,
        name: "Salami",
        price: 7000,
      },
      {
        cod: 2,
        name: "Jamón",
        price: 5000,
      },
    ],
  },
  {
    cod: 65,
    name: "Focaccia",
    img: "https://www.pequerecetas.com/wp-content/uploads/2020/11/focaccia-italiana-receta.jpg",
    type: 1,
    restaurant: 3,
    price: 25000,
    description:
      "Un pan italiano plano y horneado con aceite de oliva, ajo y hierbas, perfecto para servir como aperitivo o para hacer un sándwich.",
    aditions: [
      {
        cod: 0,
        name: "Queso",
        price: 4000,
      },
      {
        cod: 1,
        name: "Salami",
        price: 7000,
      },
      {
        cod: 2,
        name: "Jamón",
        price: 5000,
      },
    ],
  },
  {
    cod: 67,
    name: "Tiramisú",
    img: "https://cdn7.kiwilimon.com/recetaimagen/35448/960x640/42520.jpg.jpg",
    type: 2,
    restaurant: 3,
    price: 12000,
    description:
      "Un postre italiano hecho con capas de bizcochos de soletilla empapados en café y crema de mascarpone.",
    aditions: [
      {
        cod: 0,
        name: "Crema chantilly",
        price: 4000,
      },
      {
        cod: 1,
        name: "fresas",
        price: 7000,
      },
      {
        cod: 2,
        name: "Arequipe",
        price: 5000,
      },
      {
        cod: 3,
        name: "Helado",
        price: 5000,
      },
      {
        cod: 4,
        name: "Caramelo",
        price: 3000,
      },
      {
        cod: 5,
        name: "Molocotón",
        price: 8000,
      },
    ],
  },
  {
    cod: 68,
    name: "Cheesecake",
    img: "https://images.immediate.co.uk/production/volatile/sites/30/2022/10/No-bake-raspberry-cheesecake-cc1ee62.jpg",
    type: 2,
    restaurant: 3,
    price: 15000,
    description:
      "Un pastel de queso cremoso, a menudo hecho con una costra de galletas, y a menudo servcodo con una salsa de frutas o caramelo.",
    aditions: [
      {
        cod: 0,
        name: "Crema chantilly",
        price: 4000,
      },
      {
        cod: 1,
        name: "fresas",
        price: 7000,
      },
      {
        cod: 2,
        name: "Arequipe",
        price: 5000,
      },
      {
        cod: 3,
        name: "Helado",
        price: 5000,
      },
      {
        cod: 4,
        name: "Caramelo",
        price: 3000,
      },
      {
        cod: 5,
        name: "Molocotón",
        price: 8000,
      },
    ],
  },
  {
    cod: 69,
    name: "Helado frito",
    img: "https://www.rebanando.com/uploads/media/helado_frito.jpg?1383327142",
    type: 2,
    restaurant: 3,
    price: 18000,
    description:
      " Un postre clásico, a menudo servcodo en bolas con jarabe, frutas y/o nueces.",
    aditions: [
      {
        cod: 0,
        name: "Crema chantilly",
        price: 4000,
      },
      {
        cod: 1,
        name: "fresas",
        price: 7000,
      },
      {
        cod: 2,
        name: "Arequipe",
        price: 5000,
      },
      {
        cod: 3,
        name: "Helado",
        price: 5000,
      },
      {
        cod: 4,
        name: "Caramelo",
        price: 3000,
      },
      {
        cod: 5,
        name: "Molocotón",
        price: 8000,
      },
    ],
  },
  {
    cod: 70,
    name: "Brownies",
    img: "http://www.unileverfoodsolutions.com.mx/dam/global-ufs/mcos/NOLA/calcmenu/recipes/MX-recipes/In-Development/FULL-BROWNIES.png",
    type: 2,
    restaurant: 3,
    price: 15000,
    description:
      "Un pastel de chocolate denso y húmedo, a menudo servcodo con helado y/o nueces.",
    aditions: [
      {
        cod: 0,
        name: "Crema chantilly",
        price: 4000,
      },
      {
        cod: 1,
        name: "fresas",
        price: 7000,
      },
      {
        cod: 2,
        name: "Arequipe",
        price: 5000,
      },
      {
        cod: 3,
        name: "Helado",
        price: 5000,
      },
      {
        cod: 4,
        name: "Caramelo",
        price: 3000,
      },
      {
        cod: 5,
        name: "Molocotón",
        price: 8000,
      },
    ],
  },
  {
    cod: 71,
    name: "Crème brûlée",
    img: "https://www.cookingclassy.com/wp-content/uploads/2018/02/creme-brulee-7.jpg",
    type: 2,
    restaurant: 3,
    price: 20000,
    description:
      "Un postre francés hecho de crema de vainilla y cubierto con una capa de azúcar caramelizada.",
    aditions: [
      {
        cod: 0,
        name: "Crema chantilly",
        price: 4000,
      },
      {
        cod: 1,
        name: "fresas",
        price: 7000,
      },
      {
        cod: 2,
        name: "Arequipe",
        price: 5000,
      },
      {
        cod: 3,
        name: "Helado",
        price: 5000,
      },
      {
        cod: 4,
        name: "Caramelo",
        price: 3000,
      },
      {
        cod: 5,
        name: "Molocotón",
        price: 8000,
      },
    ],
  },
  {
    cod: 72,
    name: "Frutas frescas",
    img: "https://cdn0.recetasgratis.net/es/posts/1/2/5/postre_de_frutas_para_navidad_57521_orig.jpg",
    type: 2,
    restaurant: 3,
    price: 16000,
    description:
      "Una opción más saludable de postre, a menudo se sirve como una ensalada de frutas o como frutas frescas cortadas.",
    aditions: [
      {
        cod: 0,
        name: "Crema chantilly",
        price: 4000,
      },
      {
        cod: 1,
        name: "fresas",
        price: 7000,
      },
      {
        cod: 2,
        name: "Arequipe",
        price: 5000,
      },
      {
        cod: 3,
        name: "Helado",
        price: 5000,
      },
      {
        cod: 4,
        name: "Caramelo",
        price: 3000,
      },
      {
        cod: 5,
        name: "Molocotón",
        price: 8000,
      },
    ],
  },
];

export const locationsCol = [
  "Leticia",
  "Puerto Nari\u00f1o",
  "Abejorral",
  "Abriaqu\u00ed",
  "Alejandr\u00eda",
  "Amag\u00e1",
  "Amalfi",
  "Andes",
  "Angel\u00f3polis",
  "Angostura",
  "Anor\u00ed",
  "Anz\u00e1",
  "Apartad\u00f3",
  "Arboletes",
  "Argelia",
  "Armenia",
  "Barbosa",
  "Bello",
  "Belmira",
  "Betania",
  "Betulia",
  "Brice\u00f1o",
  "Buritic\u00e1",
  "C\u00e1ceres",
  "Caicedo",
  "Caldas",
  "Campamento",
  "Ca\u00f1asgordas",
  "Caracol\u00ed",
  "Caramanta",
  "Carepa",
  "Carolina del Pr\u00edncipe",
  "Caucasia",
  "Chigorod\u00f3",
  "Cisneros",
  "Ciudad Bol\u00edvar",
  "Cocorn\u00e1",
  "Concepci\u00f3n",
  "Concordia",
  "Copacabana",
  "Dabeiba",
  "Donmat\u00edas",
  "Eb\u00e9jico",
  "El Bagre",
  "El Carmen de Viboral",
  "El Pe\u00f1ol",
  "El Retiro",
  "El Santuario",
  "Entrerr\u00edos",
  "Envigado",
  "Fredonia",
  "Frontino",
  "Giraldo",
  "Girardota",
  "G\u00f3mez Plata",
  "Granada",
  "Guadalupe",
  "Guarne",
  "Guatap\u00e9",
  "Heliconia",
  "Hispania",
  "Itag\u00fc\u00ed",
  "Ituango",
  "Jard\u00edn",
  "Jeric\u00f3",
  "La Ceja",
  "La Estrella",
  "La Pintada",
  "La Uni\u00f3n",
  "Liborina",
  "Maceo",
  "Marinilla",
  "Medell\u00edn",
  "Montebello",
  "Murind\u00f3",
  "Mutat\u00e1",
  "Nari\u00f1o",
  "Nech\u00ed",
  "Necocl\u00ed",
  "Olaya",
  "Peque",
  "Pueblorrico",
  "Puerto Berr\u00edo",
  "Puerto Nare",
  "Puerto Triunfo",
  "Remedios",
  "Rionegro",
  "Sabanalarga",
  "Sabaneta",
  "Salgar",
  "San Andr\u00e9s de Cuerquia",
  "San Carlos",
  "San Francisco",
  "San Jer\u00f3nimo",
  "San Jos\u00e9 de la Monta\u00f1a",
  "San Juan de Urab\u00e1",
  "San Luis",
  "San Pedro de Urab\u00e1",
  "San Pedro de los Milagros",
  "San Rafael",
  "San Roque",
  "San Vicente",
  "Santa B\u00e1rbara",
  "Santa Fe de Antioquia",
  "Santa Rosa de Osos",
  "Santo Domingo",
  "Segovia",
  "Sons\u00f3n",
  "Sopetr\u00e1n",
  "T\u00e1mesis",
  "Taraz\u00e1",
  "Tarso",
  "Titirib\u00ed",
  "Toledo",
  "Turbo",
  "Uramita",
  "Urrao",
  "Valdivia",
  "Valpara\u00edso",
  "Vegach\u00ed",
  "Venecia",
  "Vig\u00eda del Fuerte",
  "Yal\u00ed",
  "Yarumal",
  "Yolomb\u00f3",
  "Yond\u00f3",
  "Zaragoza",
  "Arauca",
  "Arauquita",
  "Cravo Norte",
  "Fortul",
  "Puerto Rond\u00f3n",
  "Saravena",
  "Tame",
  "Baranoa",
  "Barranquilla",
  "Campo de la Cruz",
  "Candelaria",
  "Galapa",
  "Juan de Acosta",
  "Luruaco",
  "Malambo",
  "Manat\u00ed",
  "Palmar de Varela",
  "Pioj\u00f3",
  "Polonuevo",
  "Ponedera",
  "Puerto Colombia",
  "Repel\u00f3n",
  "Sabanagrande",
  "Sabanalarga",
  "Santa Luc\u00eda",
  "Santo Tom\u00e1s",
  "Soledad",
  "Su\u00e1n",
  "Tubar\u00e1",
  "Usiacur\u00ed",
  "Ach\u00ed",
  "Altos del Rosario",
  "Arenal",
  "Arjona",
  "Arroyohondo",
  "Barranco de Loba",
  "Brazuelo de Papayal",
  "Calamar",
  "Cantagallo",
  "Cartagena de Indias",
  "Cicuco",
  "Clemencia",
  "C\u00f3rdoba",
  "El Carmen de Bol\u00edvar",
  "El Guamo",
  "El Pe\u00f1\u00f3n",
  "Hatillo de Loba",
  "Magangu\u00e9",
  "Mahates",
  "Margarita",
  "Mar\u00eda la Baja",
  "Momp\u00f3s",
  "Montecristo",
  "Morales",
  "Noros\u00ed",
  "Pinillos",
  "Regidor",
  "R\u00edo Viejo",
  "San Crist\u00f3bal",
  "San Estanislao",
  "San Fernando",
  "San Jacinto del Cauca",
  "San Jacinto",
  "San Juan Nepomuceno",
  "San Mart\u00edn de Loba",
  "San Pablo",
  "Santa Catalina",
  "Santa Rosa",
  "Santa Rosa del Sur",
  "Simit\u00ed",
  "Soplaviento",
  "Talaigua Nuevo",
  "Tiquisio",
  "Turbaco",
  "Turban\u00e1",
  "Villanueva",
  "Zambrano",
  "Almeida",
  "Aquitania",
  "Arcabuco",
  "Bel\u00e9n",
  "Berbeo",
  "Bet\u00e9itiva",
  "Boavita",
  "Boyac\u00e1",
  "Brice\u00f1o",
  "Buenavista",
  "Busbanz\u00e1",
  "Caldas",
  "Campohermoso",
  "Cerinza",
  "Chinavita",
  "Chiquinquir\u00e1",
  "Ch\u00edquiza",
  "Chiscas",
  "Chita",
  "Chitaraque",
  "Chivat\u00e1",
  "Chivor",
  "Ci\u00e9nega",
  "C\u00f3mbita",
  "Coper",
  "Corrales",
  "Covarach\u00eda",
  "Cubar\u00e1",
  "Cucaita",
  "Cu\u00edtiva",
  "Duitama",
  "El Cocuy",
  "El Espino",
  "Firavitoba",
  "Floresta",
  "Gachantiv\u00e1",
  "G\u00e1meza",
  "Garagoa",
  "Guacamayas",
  "Guateque",
  "Guayat\u00e1",
  "G\u00fcic\u00e1n",
  "Iza",
  "Jenesano",
  "Jeric\u00f3",
  "La Capilla",
  "La Uvita",
  "La Victoria",
  "Labranzagrande",
  "Macanal",
  "Marip\u00ed",
  "Miraflores",
  "Mongua",
  "Mongu\u00ed",
  "Moniquir\u00e1",
  "Motavita",
  "Muzo",
  "Nobsa",
  "Nuevo Col\u00f3n",
  "Oicat\u00e1",
  "Otanche",
  "Pachavita",
  "P\u00e1ez",
  "Paipa",
  "Pajarito",
  "Panqueba",
  "Pauna",
  "Paya",
  "Paz del R\u00edo",
  "Pesca",
  "Pisba",
  "Puerto Boyac\u00e1",
  "Qu\u00edpama",
  "Ramiriqu\u00ed",
  "R\u00e1quira",
  "Rond\u00f3n",
  "Saboy\u00e1",
  "S\u00e1chica",
  "Samac\u00e1",
  "San Eduardo",
  "San Jos\u00e9 de Pare",
  "San Luis de Gaceno",
  "San Mateo",
  "San Miguel de Sema",
  "San Pablo de Borbur",
  "Santa Mar\u00eda",
  "Santa Rosa de Viterbo",
  "Santa Sof\u00eda",
  "Santana",
  "Sativanorte",
  "Sativasur",
  "Siachoque",
  "Soat\u00e1",
  "Socha",
  "Socot\u00e1",
  "Sogamoso",
  "Somondoco",
  "Sora",
  "Sorac\u00e1",
  "Sotaquir\u00e1",
  "Susac\u00f3n",
  "Sutamarch\u00e1n",
  "Sutatenza",
  "Tasco",
  "Tenza",
  "Tiban\u00e1",
  "Tibasosa",
  "Tinjac\u00e1",
  "Tipacoque",
  "Toca",
  "Tog\u00fc\u00ed",
  "T\u00f3paga",
  "Tota",
  "Tunja",
  "Tunungu\u00e1",
  "Turmequ\u00e9",
  "Tuta",
  "Tutaz\u00e1",
  "\u00dambita",
  "Ventaquemada",
  "Villa de Leyva",
  "Viracach\u00e1",
  "Zetaquira",
  "Aguadas",
  "Anserma",
  "Aranzazu",
  "Belalc\u00e1zar",
  "Chinchin\u00e1",
  "Filadelfia",
  "La Dorada",
  "La Merced",
  "Manizales",
  "Manzanares",
  "Marmato",
  "Marquetalia",
  "Marulanda",
  "Neira",
  "Norcasia",
  "P\u00e1cora",
  "Palestina",
  "Pensilvania",
  "Riosucio",
  "Risaralda",
  "Salamina",
  "Saman\u00e1",
  "San Jos\u00e9",
  "Sup\u00eda",
  "Victoria",
  "Villamar\u00eda",
  "Viterbo",
  "Albania",
  "Bel\u00e9n de los Andaqu\u00edes",
  "Cartagena del Chair\u00e1",
  "Curillo",
  "El Doncello",
  "El Paujil",
  "Florencia",
  "La Monta\u00f1ita",
  "Mil\u00e1n",
  "Morelia",
  "Puerto Rico",
  "San Jos\u00e9 del Fragua",
  "San Vicente del Cagu\u00e1n",
  "Solano",
  "Solita",
  "Valpara\u00edso",
  "Aguazul",
  "Ch\u00e1meza",
  "Hato Corozal",
  "La Salina",
  "Man\u00ed",
  "Monterrey",
  "Nunch\u00eda",
  "Orocu\u00e9",
  "Paz de Ariporo",
  "Pore",
  "Recetor",
  "Sabanalarga",
  "S\u00e1cama",
  "San Luis de Palenque",
  "T\u00e1mara",
  "Tauramena",
  "Trinidad",
  "Villanueva",
  "Yopal",
  "Almaguer",
  "Argelia",
  "Balboa",
  "Bol\u00edvar",
  "Buenos Aires",
  "Cajib\u00edo",
  "Caldono",
  "Caloto",
  "Corinto",
  "El Tambo",
  "Florencia",
  "Guachen\u00e9",
  "Guap\u00ed",
  "Inz\u00e1",
  "Jambal\u00f3",
  "La Sierra",
  "La Vega",
  "L\u00f3pez de Micay",
  "Mercaderes",
  "Miranda",
  "Morales",
  "Padilla",
  "P\u00e1ez",
  "Pat\u00eda",
  "Piamonte",
  "Piendam\u00f3",
  "Popay\u00e1n",
  "Puerto Tejada",
  "Purac\u00e9",
  "Rosas",
  "San Sebasti\u00e1n",
  "Santa Rosa",
  "Santander de Quilichao",
  "Silvia",
  "Sotar\u00e1",
  "Su\u00e1rez",
  "Sucre",
  "Timb\u00edo",
  "Timbiqu\u00ed",
  "Torib\u00edo",
  "Totor\u00f3",
  "Villa Rica",
  "Aguachica",
  "Agust\u00edn Codazzi",
  "Astrea",
  "Becerril",
  "Bosconia",
  "Chimichagua",
  "Chiriguan\u00e1",
  "Curuman\u00ed",
  "El Copey",
  "El Paso",
  "Gamarra",
  "Gonz\u00e1lez",
  "La Gloria (Cesar)",
  "La Jagua de Ibirico",
  "La Paz",
  "Manaure Balc\u00f3n del Cesar",
  "Pailitas",
  "Pelaya",
  "Pueblo Bello",
  "R\u00edo de Oro",
  "San Alberto",
  "San Diego",
  "San Mart\u00edn",
  "Tamalameque",
  "Valledupar",
  "Acand\u00ed",
  "Alto Baud\u00f3",
  "Bagad\u00f3",
  "Bah\u00eda Solano",
  "Bajo Baud\u00f3",
  "Bojay\u00e1",
  "Cant\u00f3n de San Pablo",
  "C\u00e9rtegui",
  "Condoto",
  "El Atrato",
  "El Carmen de Atrato",
  "El Carmen del Dari\u00e9n",
  "Istmina",
  "Jurad\u00f3",
  "Litoral de San Juan",
  "Llor\u00f3",
  "Medio Atrato",
  "Medio Baud\u00f3",
  "Medio San Juan",
  "N\u00f3vita",
  "Nuqu\u00ed",
  "Quibd\u00f3",
  "R\u00edo Ir\u00f3",
  "R\u00edo Quito",
  "Riosucio",
  "San Jos\u00e9 del Palmar",
  "Sip\u00ed",
  "Tad\u00f3",
  "Uni\u00f3n Panamericana",
  "Ungu\u00eda",
  "Agua de Dios",
  "Alb\u00e1n",
  "Anapoima",
  "Anolaima",
  "Apulo",
  "Arbel\u00e1ez",
  "Beltr\u00e1n",
  "Bituima",
  "Bogot\u00e1",
  "Bojac\u00e1",
  "Cabrera",
  "Cachipay",
  "Cajic\u00e1",
  "Caparrap\u00ed",
  "C\u00e1queza",
  "Carmen de Carupa",
  "Chaguan\u00ed",
  "Ch\u00eda",
  "Chipaque",
  "Choach\u00ed",
  "Chocont\u00e1",
  "Cogua",
  "Cota",
  "Cucunub\u00e1",
  "El Colegio",
  "El Pe\u00f1\u00f3n",
  "El Rosal",
  "Facatativ\u00e1",
  "F\u00f3meque",
  "Fosca",
  "Funza",
  "F\u00faquene",
  "Fusagasug\u00e1",
  "Gachal\u00e1",
  "Gachancip\u00e1",
  "Gachet\u00e1",
  "Gama",
  "Girardot",
  "Granada",
  "Guachet\u00e1",
  "Guaduas",
  "Guasca",
  "Guataqu\u00ed",
  "Guatavita",
  "Guayabal de S\u00edquima",
  "Guayabetal",
  "Guti\u00e9rrez",
  "Jerusal\u00e9n",
  "Jun\u00edn",
  "La Calera",
  "La Mesa",
  "La Palma",
  "La Pe\u00f1a",
  "La Vega",
  "Lenguazaque",
  "Machet\u00e1",
  "Madrid",
  "Manta",
  "Medina",
  "Mosquera",
  "Nari\u00f1o",
  "Nemoc\u00f3n",
  "Nilo",
  "Nimaima",
  "Nocaima",
  "Pacho",
  "Paime",
  "Pandi",
  "Paratebueno",
  "Pasca",
  "Puerto Salgar",
  "Pul\u00ed",
  "Quebradanegra",
  "Quetame",
  "Quipile",
  "Ricaurte",
  "San Antonio del Tequendama",
  "San Bernardo",
  "San Cayetano",
  "San Francisco",
  "San Juan de Rioseco",
  "Sasaima",
  "Sesquil\u00e9",
  "Sibat\u00e9",
  "Silvania",
  "Simijaca",
  "Soacha",
  "Sop\u00f3",
  "Subachoque",
  "Suesca",
  "Supat\u00e1",
  "Susa",
  "Sutatausa",
  "Tabio",
  "Tausa",
  "Tena",
  "Tenjo",
  "Tibacuy",
  "Tibirita",
  "Tocaima",
  "Tocancip\u00e1",
  "Topaip\u00ed",
  "Ubal\u00e1",
  "Ubaque",
  "Ubat\u00e9",
  "Une",
  "\u00datica",
  "Venecia",
  "Vergara",
  "Vian\u00ed",
  "Villag\u00f3mez",
  "Villapinz\u00f3n",
  "Villeta",
  "Viot\u00e1",
  "Yacop\u00ed",
  "Zipac\u00f3n",
  "Zipaquir\u00e1",
  "Ayapel",
  "Buenavista",
  "Canalete",
  "Ceret\u00e9",
  "Chim\u00e1",
  "Chin\u00fa",
  "Ci\u00e9naga de Oro",
  "Cotorra",
  "La Apartada",
  "Lorica",
  "Los C\u00f3rdobas",
  "Momil",
  "Montel\u00edbano",
  "Monter\u00eda",
  "Mo\u00f1itos",
  "Planeta Rica",
  "Pueblo Nuevo",
  "Puerto Escondido",
  "Puerto Libertador",
  "Pur\u00edsima",
  "Sahag\u00fan",
  "San Andr\u00e9s de Sotavento",
  "San Antero",
  "San Bernardo del Viento",
  "San Carlos",
  "San Jos\u00e9 de Ur\u00e9",
  "San Pelayo",
  "Tierralta",
  "Tuch\u00edn",
  "Valencia",
  "Calamar",
  "El Retorno",
  "Miraflores",
  "San Jos\u00e9 del Guaviare",
  "Acevedo",
  "Agrado",
  "Aipe",
  "Algeciras",
  "Altamira",
  "Baraya",
  "Campoalegre",
  "Colombia",
  "El Pital",
  "El\u00edas",
  "Garz\u00f3n",
  "Gigante",
  "Guadalupe",
  "Hobo",
  "\u00cdquira",
  "Isnos",
  "La Argentina",
  "La Plata",
  "N\u00e1taga",
  "Neiva",
  "Oporapa",
  "Paicol",
  "Palermo",
  "Palestina",
  "Pitalito",
  "Rivera",
  "Saladoblanco",
  "San Agust\u00edn",
  "Santa Mar\u00eda",
  "Suaza",
  "Tarqui",
  "Tello",
  "Teruel",
  "Tesalia",
  "Timan\u00e1",
  "Villavieja",
  "Yaguar\u00e1",
  "Albania",
  "Barrancas",
  "Dibulla",
  "Distracci\u00f3n",
  "El Molino",
  "Fonseca",
  "Hatonuevo",
  "La Jagua del Pilar",
  "Maicao",
  "Manaure",
  "Riohacha",
  "San Juan del Cesar",
  "Uribia",
  "Urumita",
  "Villanueva",
  "Algarrobo",
  "Aracataca",
  "Ariguan\u00ed",
  "Cerro de San Antonio",
  "Chibolo",
  "Chibolo",
  "Ci\u00e9naga",
  "Concordia",
  "El Banco",
  "El Pi\u00f1\u00f3n",
  "El Ret\u00e9n",
  "Fundaci\u00f3n",
  "Guamal",
  "Nueva Granada",
  "Pedraza",
  "Piji\u00f1o del Carmen",
  "Pivijay",
  "Plato",
  "Pueblo Viejo",
  "Remolino",
  "Sabanas de San \u00c1ngel",
  "Salamina",
  "San Sebasti\u00e1n de Buenavista",
  "San Zen\u00f3n",
  "Santa Ana",
  "Santa B\u00e1rbara de Pinto",
  "Santa Marta",
  "Sitionuevo",
  "Tenerife",
  "Zapay\u00e1n",
  "Zona Bananera",
  "Acac\u00edas",
  "Barranca de Up\u00eda",
  "Cabuyaro",
  "Castilla la Nueva",
  "Cubarral",
  "Cumaral",
  "El Calvario",
  "El Castillo",
  "El Dorado",
  "Fuente de Oro",
  "Granada",
  "Guamal",
  "La Macarena",
  "La Uribe",
  "Lejan\u00edas",
  "Mapirip\u00e1n",
  "Mesetas",
  "Puerto Concordia",
  "Puerto Gait\u00e1n",
  "Puerto Lleras",
  "Puerto L\u00f3pez",
  "Puerto Rico",
  "Restrepo",
  "San Carlos de Guaroa",
  "San Juan de Arama",
  "San Juanito",
  "San Mart\u00edn",
  "Villavicencio",
  "Vista Hermosa",
  "Aldana",
  "Ancuy\u00e1",
  "Arboleda",
  "Barbacoas",
  "Bel\u00e9n",
  "Buesaco",
  "Chachag\u00fc\u00ed",
  "Col\u00f3n",
  "Consac\u00e1",
  "Contadero",
  "C\u00f3rdoba",
  "Cuaspud",
  "Cumbal",
  "Cumbitara",
  "El Charco",
  "El Pe\u00f1ol",
  "El Rosario",
  "El Tabl\u00f3n",
  "El Tambo",
  "Francisco Pizarro",
  "Funes",
  "Guachucal",
  "Guaitarilla",
  "Gualmat\u00e1n",
  "Iles",
  "Imu\u00e9s",
  "Ipiales",
  "La Cruz",
  "La Florida",
  "La Llanada",
  "La Tola",
  "La Uni\u00f3n",
  "Leiva",
  "Linares",
  "Los Andes",
  "Mag\u00fc\u00ed Pay\u00e1n",
  "Mallama",
  "Mosquera",
  "Nari\u00f1o",
  "Olaya Herrera",
  "Ospina",
  "Pasto",
  "Policarpa",
  "Potos\u00ed",
  "Providencia",
  "Puerres",
  "Pupiales",
  "Ricaurte",
  "Roberto Pay\u00e1n",
  "Samaniego",
  "San Bernardo",
  "San Jos\u00e9 de Alb\u00e1n",
  "San Lorenzo",
  "San Pablo",
  "San Pedro de Cartago",
  "Sandon\u00e1",
  "Santa B\u00e1rbara",
  "Santacruz",
  "Sapuyes",
  "Taminango",
  "Tangua",
  "Tumaco",
  "T\u00faquerres",
  "Yacuanquer",
  "\u00c1brego",
  "Arboledas",
  "Bochalema",
  "Bucarasica",
  "C\u00e1chira",
  "C\u00e1cota",
  "Chin\u00e1cota",
  "Chitag\u00e1",
  "Convenci\u00f3n",
  "C\u00facuta",
  "Cucutilla",
  "Duran\u00eda",
  "El Carmen",
  "El Tarra",
  "El Zulia",
  "Gramalote",
  "Hacar\u00ed",
  "Herr\u00e1n",
  "La Esperanza",
  "La Playa de Bel\u00e9n",
  "Labateca",
  "Los Patios",
  "Lourdes",
  "Mutiscua",
  "Oca\u00f1a",
  "Pamplona",
  "Pamplonita",
  "Puerto Santander",
  "Ragonvalia",
  "Salazar de Las Palmas",
  "San Calixto",
  "San Cayetano",
  "Santiago",
  "Santo Domingo de Silos",
  "Sardinata",
  "Teorama",
  "Tib\u00fa",
  "Toledo",
  "Villa Caro",
  "Villa del Rosario",
  "Col\u00f3n",
  "Mocoa",
  "Orito",
  "Puerto As\u00eds",
  "Puerto Caicedo",
  "Puerto Guzm\u00e1n",
  "Puerto Legu\u00edzamo",
  "San Francisco",
  "San Miguel",
  "Santiago",
  "Sibundoy",
  "Valle del Guamuez",
  "Villagarz\u00f3n",
  "Armenia",
  "Buenavista",
  "Calarc\u00e1",
  "Circasia",
  "C\u00f3rdoba",
  "Filandia",
  "G\u00e9nova",
  "La Tebaida",
  "Montenegro",
  "Pijao",
  "Quimbaya",
  "Salento",
  "Ap\u00eda",
  "Balboa",
  "Bel\u00e9n de Umbr\u00eda",
  "Dosquebradas",
  "Gu\u00e1tica",
  "La Celia",
  "La Virginia",
  "Marsella",
  "Mistrat\u00f3",
  "Pereira",
  "Pueblo Rico",
  "Quinch\u00eda",
  "Santa Rosa de Cabal",
  "Santuario",
  "Providencia y Santa Catalina Islas",
  "San Andr\u00e9s",
  "Aguada",
  "Albania",
  "Aratoca",
  "Barbosa",
  "Barichara",
  "Barrancabermeja",
  "Betulia",
  "Bol\u00edvar",
  "Bucaramanga",
  "Cabrera",
  "California",
  "Capitanejo",
  "Carcas\u00ed",
  "Cepit\u00e1",
  "Cerrito",
  "Charal\u00e1",
  "Charta",
  "Chima",
  "Chipat\u00e1",
  "Cimitarra",
  "Concepci\u00f3n",
  "Confines",
  "Contrataci\u00f3n",
  "Coromoro",
  "Curit\u00ed",
  "El Carmen de Chucur\u00ed",
  "El Guacamayo",
  "El Pe\u00f1\u00f3n",
  "El Play\u00f3n",
  "El Socorro",
  "Encino",
  "Enciso",
  "Flori\u00e1n",
  "Floridablanca",
  "Gal\u00e1n",
  "G\u00e1mbita",
  "Gir\u00f3n",
  "Guaca",
  "Guadalupe",
  "Guapot\u00e1",
  "Guavat\u00e1",
  "G\u00fcepsa",
  "Hato",
  "Jes\u00fas Mar\u00eda",
  "Jord\u00e1n",
  "La Belleza",
  "La Paz",
  "Land\u00e1zuri",
  "Lebrija",
  "Los Santos",
  "Macaravita",
  "M\u00e1laga",
  "Matanza",
  "Mogotes",
  "Molagavita",
  "Ocamonte",
  "Oiba",
  "Onzaga",
  "Palmar",
  "Palmas del Socorro",
  "P\u00e1ramo",
  "Piedecuesta",
  "Pinchote",
  "Puente Nacional",
  "Puerto Parra",
  "Puerto Wilches",
  "Rionegro",
  "Sabana de Torres",
  "San Andr\u00e9s",
  "San Benito",
  "San Gil",
  "San Joaqu\u00edn",
  "San Jos\u00e9 de Miranda",
  "San Miguel",
  "San Vicente de Chucur\u00ed",
  "Santa B\u00e1rbara",
  "Santa Helena del Op\u00f3n",
  "Simacota",
  "Suaita",
  "Sucre",
  "Surat\u00e1",
  "Tona",
  "Valle de San Jos\u00e9",
  "V\u00e9lez",
  "Vetas",
  "Villanueva",
  "Zapatoca",
  "Buenavista",
  "Caimito",
  "Chal\u00e1n",
  "Colos\u00f3",
  "Corozal",
  "Cove\u00f1as",
  "El Roble",
  "Galeras",
  "Guaranda",
  "La Uni\u00f3n",
  "Los Palmitos",
  "Majagual",
  "Morroa",
  "Ovejas",
  "Sampu\u00e9s",
  "San Antonio de Palmito",
  "San Benito Abad",
  "San Juan de Betulia",
  "San Marcos",
  "San Onofre",
  "San Pedro",
  "Sinc\u00e9",
  "Sincelejo",
  "Sucre",
  "Tol\u00fa",
  "Tol\u00fa Viejo",
  "Alpujarra",
  "Alvarado",
  "Ambalema",
  "Anzo\u00e1tegui",
  "Armero",
  "Ataco",
  "Cajamarca",
  "Carmen de Apical\u00e1",
  "Casabianca",
  "Chaparral",
  "Coello",
  "Coyaima",
  "Cunday",
  "Dolores",
  "El Espinal",
  "Fal\u00e1n",
  "Flandes",
  "Fresno",
  "Guamo",
  "Herveo",
  "Honda",
  "Ibagu\u00e9",
  "Icononzo",
  "L\u00e9rida",
  "L\u00edbano",
  "Mariquita",
  "Melgar",
  "Murillo",
  "Natagaima",
  "Ortega",
  "Palocabildo",
  "Piedras",
  "Planadas",
  "Prado",
  "Purificaci\u00f3n",
  "Rioblanco",
  "Roncesvalles",
  "Rovira",
  "Salda\u00f1a",
  "San Antonio",
  "San Luis",
  "Santa Isabel",
  "Su\u00e1rez",
  "Valle de San Juan",
  "Venadillo",
  "Villahermosa",
  "Villarrica",
  "Alcal\u00e1",
  "Andaluc\u00eda",
  "Ansermanuevo",
  "Argelia",
  "Bol\u00edvar",
  "Buenaventura",
  "Buga",
  "Bugalagrande",
  "Caicedonia",
  "Cali",
  "Calima",
  "Candelaria",
  "Cartago",
  "Dagua",
  "El \u00c1guila",
  "El Cairo",
  "El Cerrito",
  "El Dovio",
  "Florida",
  "Ginebra",
  "Guacar\u00ed",
  "Jamund\u00ed",
  "La Cumbre",
  "La Uni\u00f3n",
  "La Victoria",
  "Obando",
  "Palmira",
  "Pradera",
  "Restrepo",
  "Riofr\u00edo",
  "Roldanillo",
  "San Pedro",
  "Sevilla",
  "Toro",
  "Trujillo",
  "Tulu\u00e1",
  "Ulloa",
  "Versalles",
  "Vijes",
  "Yotoco",
  "Yumbo",
  "Zarzal",
  "Carur\u00fa",
  "Mit\u00fa",
  "Taraira",
  "Cumaribo",
  "La Primavera",
  "Puerto Carre\u00f1o",
  "Santa Rosal\u00eda",
];
